spring:
  config:
    activate:
      on-profile: real
  datasource:
    url: ${REAL_DB_URL}
    username: ${REAL_DB_USERNAME}
    password: ${REAL_DB_PASSWORD}

tourwave:
  environment: real
  runtime-mode: production

integration:
  payment:
    base-url: ${REAL_PAYMENT_BASE_URL}
    api-key: ${REAL_PAYMENT_API_KEY}
  notification:
    base-url: ${REAL_NOTIFICATION_BASE_URL}
    api-key: ${REAL_NOTIFICATION_API_KEY}
  asset:
    base-url: ${REAL_ASSET_BASE_URL}
    access-token: ${REAL_ASSET_ACCESS_TOKEN}
