spring:
  config:
    activate:
      on-profile: mysql-test
  datasource:
    url: jdbc:h2:mem:tourwave;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: false
  main:
    allow-bean-definition-overriding: true

tourwave:
  persistence:
    hibernate-dialect: org.hibernate.dialect.H2Dialect
    hbm2ddl-auto: create-drop
  auth:
    allow-header-auth-fallback: true
