package com.demo.tourwave.domain.common

enum class ErrorCode {
    UNAUTHORIZED,
    FORBIDDEN,
    VALIDATION_ERROR,
    REQUIRED_FIELD_MISSING,
    BOOKING_SCOPE_MISMATCH,
    ATTENDANCE_NOT_ELIGIBLE,
    DUPLICATE_REVIEW,
    PARTY_SIZE_OUT_OF_RANGE,
    INVALID_STATE_TRANSITION,
    BOOKING_TERMINAL_STATE,
    OFFER_NOT_ACTIVE,
    OFFER_EXPIRED,
    OCCURRENCE_ALREADY_CANCELED,
    CAPACITY_EXCEEDED,
    PARTY_SIZE_INCREASE_NOT_ALLOWED,
    IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD,
    IDEMPOTENCY_IN_PROGRESS
}
