ALTER TABLE occurrences ADD COLUMN end_at_utc DATETIME(6) NULL;
ALTER TABLE occurrences ADD COLUMN unit_price INT NOT NULL DEFAULT 0;
ALTER TABLE occurrences ADD COLUMN currency VARCHAR(3) NOT NULL DEFAULT 'KRW';
ALTER TABLE occurrences ADD COLUMN location_text VARCHAR(255) NULL;
ALTER TABLE occurrences ADD COLUMN meeting_point VARCHAR(500) NULL;
ALTER TABLE occurrences ADD COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE occurrences ADD COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

UPDATE occurrences
SET updated_at = created_at
WHERE updated_at IS NULL;
