ALTER TABLE occurrences ADD COLUMN IF NOT EXISTS end_at_utc DATETIME(6) NULL;
ALTER TABLE occurrences ADD COLUMN IF NOT EXISTS unit_price INT NOT NULL DEFAULT 0;
ALTER TABLE occurrences ADD COLUMN IF NOT EXISTS currency VARCHAR(3) NOT NULL DEFAULT 'KRW';
ALTER TABLE occurrences ADD COLUMN IF NOT EXISTS location_text VARCHAR(255) NULL;
ALTER TABLE occurrences ADD COLUMN IF NOT EXISTS meeting_point VARCHAR(500) NULL;
ALTER TABLE occurrences ADD COLUMN IF NOT EXISTS created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE occurrences ADD COLUMN IF NOT EXISTS updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

UPDATE occurrences
SET updated_at = created_at
WHERE updated_at IS NULL;
